# Scikit learn
A library for creating machine learning model

__What are going to be covered:__

0. An end-to-end scikit learn workflow
1. Getting the data ready
2. Choose the right estimator/model for the data
3. Fit the model/algorithm to the data to make predictions
4. Evaluate the model
5. Improving the model
6. saving the model
7. Put it all together

In [1]:
#1. getting the data ready
import numpy as np
import pandas as pd

In [2]:
heart_disease = pd.read_csv("heart-disease.csv")
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [3]:
X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

In [4]:
# 2. choose the right model
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()

In [5]:
# 3. fit the model
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

In [6]:
clf.fit(X_train, y_train)

RandomForestClassifier()

In [7]:
y_preds = clf.predict(X_test)

In [8]:
clf.score(X_test, y_test)

0.819672131147541

In [9]:
# 4. evaluate the model
from sklearn.metrics import classification_report, accuracy_score

In [10]:
accuracy_score(y_test, y_preds)

0.819672131147541

In [11]:
import pickle
pickle.dump(clf, open("heart-disease-analysis.pkl", "wb"))

In [12]:
loaded_model = pickle.load(open("heart-disease-analysis.pkl", "rb"))
loaded_model.score(X_test, y_test)

0.819672131147541

In [13]:
import sklearn
sklearn.show_versions()


System:
    python: 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\snehal\anaconda3\python.exe
   machine: Windows-10-10.0.19041-SP0

Python dependencies:
          pip: 20.2.4
   setuptools: 50.3.1.post20201107
      sklearn: 0.24.2
        numpy: 1.19.2
        scipy: 1.5.2
       Cython: 0.29.21
       pandas: 1.1.3
   matplotlib: 3.3.2
       joblib: 0.17.0
threadpoolctl: 2.1.0

Built with OpenMP: True


In [14]:
#standard imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

## 1. Getting data ready for the machine learning model

Three main things we have to do:

1. split the data into features and labels(usually X and y)
2. filling (also  called __imputing__) or disregarding the missing value
3. converting the non-numerical values to numerical values (also called __feature encoding__)

In [15]:
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [16]:
# 1. split the data
X = heart_disease.drop("target", axis=1)
X

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  
0        0   0     1  
1        0   0     2  
2        2   0     2  
3        2   0     2  
4        2   0     2  
..     ...  ..   ...  
298      1   0     3  
299      1   0     3  
300      1   2     3  
301      1   1     3  
302      1   1     2  

[303 rows x 13 columns]

In [17]:
y = heart_disease["target"]

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [19]:
X_train.shape

(242, 13)

#### 1.1 Make sure all the data are numerical

In [20]:
car_sales = pd.read_csv("car-sales-extended.csv")

In [21]:
car_sales.head()

Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [22]:
car_sales.shape

(1000, 5)

In [23]:
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price             int64
dtype: object

In [24]:
X = car_sales.drop("Price", axis=1)
y = car_sales["Price"]

In [25]:
#converting non-numerical values into numerical values
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_values = ["Make","Colour","Doors"]

one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot", one_hot, categorical_values)],
                                 remainder="passthrough")

transformed_X = transformer.fit_transform(X)
transformed_X

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [26]:
pd.DataFrame(transformed_X)

0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

### 1.2 What if there were missing data?

1. fill them with some values(also called as imputation)
2. remove the samples with missing data altogether

In [27]:
car_sales_missing = pd.read_csv("car-sales-extended-missing-data.csv")
car_sales_missing.head()

Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [28]:
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

### option 1: handling the missing data with pandas

In [29]:
#fill the Make column
car_sales_missing["Make"].fillna("missing", inplace=True)

#fill the Colour column
car_sales_missing["Colour"].fillna("missing", inplace=True)

#fill the Odometer column
car_sales_missing["Odometer (KM)"].fillna(car_sales_missing["Odometer (KM)"].mean(), inplace=True)

#fill the Doors column
car_sales_missing["Doors"].fillna(car_sales_missing["Doors"].mean(), inplace=True)

In [30]:
#remove the sample with empty Price column
car_sales_missing.dropna(inplace=True)

In [31]:
car_sales_missing.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [32]:
len(car_sales_missing)

950

### option 2 : handling the missing data with scikit learn

In [33]:
car_sales_missing = pd.read_csv("car-sales-extended-missing-data.csv")
car_sales_missing

Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [34]:
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [35]:
#drop the values with no price
car_sales_missing.dropna(subset=["Price"], inplace=True)

In [36]:
car_sales_missing.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [37]:
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

cat_imputer = SimpleImputer(strategy="constant", fill_value="missing")
door_imputer = SimpleImputer(strategy="constant", fill_value=4)
num_imputer = SimpleImputer(strategy="mean")

## 2. choosing the right estimator

* classification - predicting either one of them
* regression - predicting the number

### 2.1 solving the regression problem

In [38]:
from sklearn.datasets import load_boston
boston = load_boston()
boston_df = pd.DataFrame(boston["data"], 
                         columns=boston["feature_names"])
boston_df["target"] = pd.Series(boston["target"])

In [39]:
boston_df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [40]:
len(boston_df)

506

In [41]:
X = boston_df.drop("target",axis=1)
y = boston_df["target"]

In [42]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [43]:
#choose the Ridge regression
from sklearn.linear_model import Ridge
rid = Ridge()

rid.fit(X_train, y_train)

rid.score(X_test, y_test)

0.6471527283367842

In [44]:
#choosing the RandomForestRegressor regression
from sklearn.ensemble import RandomForestRegressor

rfr = RandomForestRegressor(n_estimators=10)

rfr.fit(X_train, y_train)

rfr.score(X_test, y_test)

0.8238614748031996

### 2.2 solving the classification problem

In [45]:
from sklearn.datasets import load_iris
iris = load_iris()
iris_df = pd.DataFrame(iris["data"],
                       columns=iris["feature_names"])
iris_df["target"] = pd.Series(iris["target"])

iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [46]:
#splitting the data
X = iris_df.drop("target", axis=1)
y = iris_df["target"]

In [47]:
#splitting the data into training and test data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [48]:
#choosing the LinearSVC classification model
from sklearn.svm import LinearSVC
lsvc = LinearSVC()

lsvc.fit(X_train, y_train)

lsvc.score(X_test, y_test)

C:\Users\snehal\anaconda3\lib\site-packages\sklearn\svm\_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


0.9333333333333333

In [49]:
#choosing the RandomForestClassifier classification model
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=10)

rfc.fit(X_train, y_train)

rfc.score(X_test, y_test)

0.9666666666666667

#### Heart Disease Prediction Problem

Predict Whether the patient has heart disease or dont't have heart disease

In [50]:
heart_disease = pd.read_csv("heart-disease.csv")
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [51]:
#splitting the data
X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

In [52]:
#splitting the data into training and testing 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [53]:
#choosing the RandomForestClassifier classification
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=25)

np.random.seed(42)
rfc.fit(X_train, y_train)

rfc.score(X_test, y_test)

0.819672131147541

## Fitting the data to the model

### 3.1 Fit the model to data

In [54]:
X.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [55]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [56]:
y.tail()

298    0
299    0
300    0
301    0
302    0
Name: target, dtype: int64

In [57]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=25)

np.random.seed(42)
rfc.fit(X_train, y_train)

rfc.score(X_test, y_test)

0.819672131147541

In [58]:
rfc.predict(X_test[:5])

array([1, 1, 0, 0, 1], dtype=int64)

In [59]:
rfc.predict_proba(X_test[:5])

array([[0.  , 1.  ],
       [0.4 , 0.6 ],
       [0.6 , 0.4 ],
       [0.52, 0.48],
       [0.12, 0.88]])

`predict()` can also be used for regression

In [60]:
boston_df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [61]:
X = boston_df.drop("target", axis=1)
y = boston_df["target"]

In [62]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [63]:
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor()

rfr.fit(X_train, y_train)

RandomForestRegressor()

In [64]:
y_preds = rfr.predict(X_test)

In [65]:
y_preds[:5]

array([19.943,  9.884, 20.544, 34.059, 20.979])

In [66]:
y_test[:5]

312    19.4
392     9.7
6      22.9
281    35.4
78     21.2
Name: target, dtype: float64

In [67]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_preds)

1.661450980392155

## 4 Evaluating machine learning model

Three ways of evaluating machine learnig model/estimators
1. estimator `score` method
2. the `scoring` parameter
3. problem speficif `metric` function

### 4.1 `score` method

_for the classification...._

`score` uses mean accuracy

In [68]:
from sklearn.ensemble import RandomForestClassifier

np.random.seed(42)

X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

clf = RandomForestClassifier()

clf.fit(X_train, y_train)

clf.score(X_test, y_test)

0.8524590163934426

_for the regression....._

`score` uses coefficient of determination

In [69]:
from sklearn.ensemble import RandomForestRegressor

np.random.seed(42)

X = boston_df.drop("target", axis=1)
y = boston_df["target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

rfr = RandomForestRegressor()

rfr.fit(X_train, y_train)

rfr.score(X_test, y_test)

0.8654448653350507

### 4.2 the `scoring` parameter

In [70]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

np.random.seed(42)

X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

clf = RandomForestClassifier()
clf.fit(X_train, y_train)
cross_val_score(clf, X,y, cv=5)

array([0.81967213, 0.86885246, 0.81967213, 0.78333333, 0.76666667])

### 4.2.1 classification model evaluation metrics

1. Accuracy
2. area under roc curve
3. confusion matrix
4. classification report

**Accuracy**

In [71]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

np.random.seed(42)

X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

clf = RandomForestClassifier()
clf.fit(X_train, y_train)

RandomForestClassifier()

In [72]:
cross_val_score = np.mean(cross_val_score(clf, X, y, cv=5))
cross_val_score

0.811639344262295

In [73]:
print(f"Heart Disease Classifier Cross Validated Accuracy {cross_val_score* 100:.2f}%")

Heart Disease Classifier Cross Validated Accuracy 81.16%


**Area under ROC(receiver operating characteristic) curve**

ROC curve is comparison of model's True positive rate(TPR) versus False Positive Rate(FPR)

* True Positive - the model predicts 1 when truth is 1
* False Positive - the model preditcs 1 when truth is 0
* True negatics - the model predicts 0 when truth is 0
* False negative - the model predicts 0 when truth is 1

In [78]:
from sklearn.metrics import roc_curve

clf.fit(X_train, y_train)

y_probs = clf.predict_proba(X_test)

y_probs = y_probs[:10]
y_probs

array([[0.9 , 0.1 ],
       [0.5 , 0.5 ],
       [0.53, 0.47],
       [0.93, 0.07],
       [0.24, 0.76],
       [0.1 , 0.9 ],
       [0.28, 0.72],
       [0.96, 0.04],
       [0.97, 0.03],
       [0.47, 0.53]])

In [79]:
y_probs_positive = y_probs[:, 1]
y_probs_positive

array([0.1 , 0.5 , 0.47, 0.07, 0.76, 0.9 , 0.72, 0.04, 0.03, 0.53])